Improve UX of Squit package chooser
hpi-swa/Squot pull request #346
Opened 2021-10-26 20:17 UTC by LinqLover

- Add support for multiselection (251a8e5)
- Add cancel button (6f3dcd1)
- Use theme colors for buttons (6f3dcd1)

2021-12-17 20:41 UTC, j4yk requested changes

2022-09-09 16:21 UTC, LinqLover commented on src/Squit.package/SquitPackageChooser.class/instance/track..st
> +	selectedTrackedPackages add: aPackage.
Thank you for the review! Good catch, conflicts were an edge case that I had missed completely. I have now revised this via 57b088d by removing all conflicts from the multiselection before tracking it. Do you think this is okay?

2022-09-09 16:21 UTC, LinqLover commented on src/Squit.package/SquitPackageChooser.class/instance/track..st
> +		[:p | packageInfo includesSystemCategory: p].
Please see v57b088d/my comment above (https://github.com/hpi-swa/Squot/pull/346#discussion_r967253538)

2022-09-09 16:28 UTC, LinqLover commented on src/Squit.package/SquitPackageChooser.class/instance/untrack..st
> +	self changed: #selectionsUntrackedAt:.
You are addressing two points here, right?

1. Scroll newly tracked/untracked package into view: Obviously, this can only be done for one package if they are not located together. I have implemented that via 97619a5 by single-selecting the new item (the Morphic vocabulary here is unfortunately overloaded: a multi-selection list has both a (single) "selection" (`#getIndex`/`#setIndex` or `#getSelected`/`#setSelected`) and a "selection list" (`#getSelectionList`/`#setSelectionList`). Only the single selection is used to scroll an item into view).

2. Selecting/unselecting items: To my knowledge, the common ToolBuilder pattern for allowing the user to control selections is to offer them a few "select all/select none/select inversion" options in the yellow-button menu of the list. If you deem this important, I can add such a feature. Interested?

2022-09-11 14:44 UTC, j4yk commented on src/Squit.package/SquitPackageChooser.class/instance/track..st
> +	selectedTrackedPackages add: aPackage.
Thank you for the new set of commits!

What gets added to the right list is now correct, and the selectedTrackedPackages are as well. But the selectedUntrackedPackages inst var still retains the "conflict" items. Since you cannot click on them, you cannot remove them from there either. It may not functionally break anything, but it makes the answers of certain query methods wrong, such as hasUntrackedSelections and selectedUntrackedPackages.

It does have an upside to it as well, but it is rather unexpected: if you select 60Deprecated and 60Deprecated-Collections, only the former will be added (and the later stays in the selectedUntrackedPackages); but if you untrack 60Deprecated again in the same session with the dialog, the 60Deprecated-Collections will reappear and be selected again, just as it was when you pushed the ">" button which had it disappear. But unfortunately this will also happen if you have dealt with other packages in the meantime, so I do not think this is worth preserving because it is too confusing/complex.

2022-09-11 14:55 UTC, j4yk commented on src/Squit.package/SquitPackageChooser.class/instance/untrack..st
> +	self changed: #selectionsUntrackedAt:.
Scrolling into view works nicely now, thank you. Your mention of the list manipulation actions reminds me of the Test Runner, which in turn reminds me that I have already seen the "focus item among multiple selected items" there. You have to click it right if you want to use the "Browse" action to browse a particular test class from the list...

I do not think that we need the full set here. In particular, select all and select inversion would not do any good most of the time. Select none could be useful though.

What I noticed when trying this out again is that, despite the scroll into view feature, I tend to forget that I still have something selected outside of the view. For example, select 60Deprecated in the untracked packages, then remove a package from your project, 60Deprecated stays selected and is easily forgotten. Likewise you can forget it if you just scroll down to search for something else. Subsequently I am surprised when I use the ">" button.

In a way, it would be more intuitive if you could only select consecutive blocks of categories... and if you start another selection, the previous one would be cleared. Much like Windows list views behave, but that's Squeak widgets vs. Windows widgets gestures...

Not having that -- and honestly the dialog is so seldom used that it may not be worth all the attention -- should we add something simpler like an indicator how many packages are selected? Or a label below the left list that reads "Selected: 60Deprecated, Balloon, Gofer" (it could undergo the elimination of sub-packages already, or not)? Could be in another pull request, in order not to halt this one much longer.

2022-09-11 15:00 UTC, j4yk commented on src/Squit.package/SquitPackageChooser.class/instance/untrack..st
> +	self changed: #selectionsUntrackedAt:.
Or overwrite the previous untracked selection when packages get untracked. So that after something gets untracked, only those untracked packages are selected, not anything that was previously selected. It would not completely solve the forgotten selection problem if you untrack Etoys and WebClient simultaneously, but may still be batter than keeping the previous selection. You could also select nothing and just scroll the first of the removed into view.

What do you think is the most acceptable tradeoff between usability/predictability and simple implementation?

2022-09-11 15:01 UTC, j4yk commented
Unless absolutely necessary to implement the feature under review, please avoid merging the upstream branches into pull requests.

2022-09-13 18:02 UTC, LinqLover commented on src/Squit.package/SquitPackageChooser.class/instance/track..st
> +	selectedTrackedPackages add: aPackage.
Thank you!

> But the selectedUntrackedPackages inst var still retains the "conflict" items.

Yes, this does not make great sense and was unintentional. Fixed via 587e6a4.

2022-09-13 18:06 UTC, LinqLover commented on src/Squit.package/SquitPackageChooser.class/instance/untrack..st
> +	self changed: #selectionsUntrackedAt:.
Option 2 makes much more sense to me - it provides a simple direct-manipulation style for undoing any track/untrack button. Implemented via 587e6a4.

Regarding the list selection, I have added a simple "select none"/"select inversion"/"select all" menu to each package list in the dialog (d98d888). I think the second and the third option could make sense too indeed:

> While most of the time, "select none" may be of the greatest interest, the other two options "select all" and "selection inversion" fulfill two purposes: Not only offer they familiarity to the user (see also the test runner or the change list), but also might they become useful if the user is interacting in a different environment than Smalltalk where the total number of packages could be much smaller.

How do you like it? :)

2022-09-13 18:10 UTC, LinqLover commented
> Unless absolutely necessary to implement the feature under review, please avoid merging the upstream branches into pull requests. It makes it harder to find all the changes that the branch introduces.

Alright, great idea, will do it in the future! In this particular case, GitHub reports a merge conflict, though ...

(Just curious: What tools make it harder for you to find all the changes from a branch? Unless you create a defect merge commit due to https://github.com/hpi-swa/Squot/issues/53 or https://github.com/hpi-swa/Squot/issues/199, I think GitHub will display the right diff anyway. Is Squot missing a similar capability? :))

2022-09-14 19:50 UTC, j4yk commented on src/Squit.package/SquitPackageChooser.class/instance/untrack..st
> +	self changed: #selectionsUntrackedAt:.
Well, the "in another environment" example seems a bit far-fetched to me (and if the list of packages is short there is also less need for the menu items), but now that the code is already there I see no harm in it.

2022-09-14 20:11 UTC, j4yk commented
> In this particular case, GitHub reports a merge conflict, though ...

That's life if it goes on on the target branch. :-) You could rebase the feature, or pretend to merge into upstream (not the other way around) and push that to the feature branch instead of to the upstream branch (the merge commit will have the upstream branch as its first parent, not as its second as in your merges—and the commit message will indicate the upstream branch as the target, obviously). Actually the command line instructions GitHub gives to merge manually produce about the same result.

> (Just curious: What tools make it harder for you to find all the changes from a branch? 

Umm actually I gave the wrong reason. The real one is that the branch does no longer contain only its own changes and kind-of changes its base in the middle of its commit stream, which can make backporting harder. But actually backporting does not really happen in this repository. This is the influence from my job chiming in, where we do have to backport/rebase features every once in a while to supply older releases with service packs. Still, not merging the upstream at least keeps the history cleaner.

2022-09-14 20:28 UTC, j4yk commented on src/Squit.package/SquitPackageChooser.class/instance/chooseFor..st
> +	trackedPackages := (self packagesIn: aWorkingCopy) asSortedCollection.
The order in fact does matter (for loading). But arguably this is not of much concern in the package chooser.

2022-09-14 20:30 UTC, merged

2022-09-15 10:23 UTC, LinqLover commented
Thanks for the explanation, and thanks for the review! 🎉